"""The Visual IR: the source of truth for every animation.

This package defines what an animation *is* -- semantically, with no reference to
Manim, coordinates, frame numbers or aspect ratios. Those belong to the compiler
and the renderer. Everything here is a Pydantic model, so the schema is
executable: it validates, it serializes, and it generates the JSON Schema that
every other layer derives its types from.

The public surface is deliberately flat. Import from ``manorem_ir``, not from
its submodules, so internal reorganization stays internal.
"""

from __future__ import annotations

from manorem_ir.audio import AudioClip, AudioTimeline, MusicBed
from manorem_ir.camera import CameraSpec, CameraState
from manorem_ir.enums import (
    CAMERA_OPS,
    Aspect,
    ClaimKind,
    Easing,
    LayoutKind,
    NarrationRole,
    ObjectKind,
    RelationKind,
    SemanticOp,
    Side,
    TransitionKind,
)
from manorem_ir.format import (
    FPS_BY_QUALITY,
    RESOLUTIONS,
    FormatSpec,
    StyleTokens,
)
from manorem_ir.geometry import (
    ORIGIN,
    SAFE_AREA,
    StageBounds,
    StagePoint,
    StageSize,
    union_all,
)
from manorem_ir.layout import Align, LayoutSlot, LayoutSpec
from manorem_ir.narration import DEFAULT_WPM, NarrationSegment
from manorem_ir.objects import (
    AnchorPlacement,
    AutoPlacement,
    Group,
    ObjectStyle,
    Placement,
    Relationship,
    SceneObject,
    SlotPlacement,
    StagePlacement,
)
from manorem_ir.operations import (
    ANY_KIND,
    CORE_OPERATIONS,
    DEFAULT_REGISTRY,
    OperationDecl,
    OperationRegistry,
    ParamDecl,
)
from manorem_ir.project import IR_VERSION, Episode, Project
from manorem_ir.props import (
    ArrowProps,
    AxesProps,
    ChartProps,
    ChartSeries,
    CircleProps,
    DiagramProps,
    DotProps,
    GlobeProps,
    GraphEdge,
    GraphNode,
    GraphProps,
    GroupProps,
    IconProps,
    ImageProps,
    LineProps,
    MapProps,
    MathProps,
    NetworkProps,
    ObjectProps,
    ParticlesProps,
    PolygonProps,
    RectangleProps,
    SvgProps,
    TextProps,
    TimelineEntry,
    TimelineProps,
)
from manorem_ir.resolve import ResolvedTiming, Window, narration_windows, resolve_timing
from manorem_ir.scene import CUT, Scene, Transition
from manorem_ir.schema import (
    SCHEMA_MODELS,
    all_schemas,
    export_schemas,
    schema_digest,
    schema_for,
)
from manorem_ir.timeline import Cue, ParamValue
from manorem_ir.timing import (
    AUTO,
    AbsoluteTime,
    AfterCue,
    AutoDuration,
    DurationExpr,
    NarrationDuration,
    NarrationTime,
    SecondsDuration,
    TimeExpr,
    WithCue,
    after,
    at_narration,
    at_seconds,
    lasting,
    referenced_cue,
    referenced_segment,
    spanning,
    with_cue,
)
from manorem_ir.validate import (
    SceneConstraint,
    ValidationContext,
    ValidationPolicy,
    check_geometry,
    diagnostics_from_validation_error,
    parse_project,
    scene_duration,
    validate_project,
    validate_scene,
)

__all__ = [
    "ANY_KIND",
    "AUTO",
    "CAMERA_OPS",
    "CORE_OPERATIONS",
    "CUT",
    "DEFAULT_REGISTRY",
    "DEFAULT_WPM",
    "FPS_BY_QUALITY",
    "IR_VERSION",
    "ORIGIN",
    "RESOLUTIONS",
    "SAFE_AREA",
    "SCHEMA_MODELS",
    "AbsoluteTime",
    "AfterCue",
    "Align",
    "AnchorPlacement",
    "ArrowProps",
    "Aspect",
    "AudioClip",
    "AudioTimeline",
    "AutoDuration",
    "AutoPlacement",
    "AxesProps",
    "CameraSpec",
    "CameraState",
    "ChartProps",
    "ChartSeries",
    "CircleProps",
    "ClaimKind",
    "Cue",
    "DiagramProps",
    "DotProps",
    "DurationExpr",
    "Easing",
    "Episode",
    "FormatSpec",
    "GlobeProps",
    "GraphEdge",
    "GraphNode",
    "GraphProps",
    "Group",
    "GroupProps",
    "IconProps",
    "ImageProps",
    "LayoutKind",
    "LayoutSlot",
    "LayoutSpec",
    "LineProps",
    "MapProps",
    "MathProps",
    "MusicBed",
    "NarrationDuration",
    "NarrationRole",
    "NarrationSegment",
    "NarrationTime",
    "NetworkProps",
    "ObjectKind",
    "ObjectProps",
    "ObjectStyle",
    "OperationDecl",
    "OperationRegistry",
    "ParamDecl",
    "ParamValue",
    "ParticlesProps",
    "Placement",
    "PolygonProps",
    "Project",
    "RectangleProps",
    "RelationKind",
    "Relationship",
    "ResolvedTiming",
    "Scene",
    "SceneConstraint",
    "SceneObject",
    "SecondsDuration",
    "SemanticOp",
    "Side",
    "SlotPlacement",
    "StageBounds",
    "StagePlacement",
    "StagePoint",
    "StageSize",
    "StyleTokens",
    "SvgProps",
    "TextProps",
    "TimeExpr",
    "TimelineEntry",
    "TimelineProps",
    "Transition",
    "TransitionKind",
    "ValidationContext",
    "ValidationPolicy",
    "Window",
    "WithCue",
    "after",
    "all_schemas",
    "at_narration",
    "at_seconds",
    "check_geometry",
    "diagnostics_from_validation_error",
    "export_schemas",
    "lasting",
    "narration_windows",
    "parse_project",
    "referenced_cue",
    "referenced_segment",
    "resolve_timing",
    "scene_duration",
    "schema_digest",
    "schema_for",
    "spanning",
    "union_all",
    "validate_project",
    "validate_scene",
    "with_cue",
]
